//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuade25.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;
    using System.Linq;

    public partial class HoaDonBanSach
    {
        [Key]
        public int MaHD { get; set; }
        [Required]
        public int MaSach { get; set; }
        [StringLength(50,MinimumLength =5)]
        public string KhachHang { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]
        public System.DateTime NgayBan { get; set; }
        [Range(1,int .MaxValue)]
        public int SoLuong { get; set; }
        //nhận đơn giá
        public decimal DonGia => Sach?.DonGia ?? 0;
       
        public decimal ThanhTien => SoLuong * DonGia;
        // Kiểm tra số lượng nhập phải nhỏ hơn số lượng tồn
        public bool KTSoLuong(QLSachEntities db)
        {
            // Lấy số lượng tồn của mã sách
            var s = db.Saches.FirstOrDefault(m => m.MaSach== this.MaSach);
            if (s == null)
            {
                return false;  
            }
            // Kiểm tra số lượng đặt không vượt quá số lượng tồn
            return this.SoLuong <= s.SoLuongTon;
        }
        public virtual Sach Sach { get; set; }
    }
}
