//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuade25.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;
    using System.Linq;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.HoaDonBanSaches = new HashSet<HoaDonBanSach>();
        }
        [Key]
        public int MaSach { get; set; }
        [Required(ErrorMessage ="Phải nhập")]
        [StringLength(50,MinimumLength =5,ErrorMessage ="Chiều dài từ 5-50 ký tự")]
        public string TenSach { get; set; }
        [Required(ErrorMessage = "Phải nhập")]
       //  [StringLength(50, MinimumLength = 5, ErrorMessage = "Chiều dài từ 5-50 ký tự")] - vì thể loại dùng Dropdowlist nên k cần tạo chú thích     
        public string TheLoai { get; set; }
        [Required(ErrorMessage = "Phải nhập")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Chiều dài từ 5-50 ký tự")]
        public string TacGia { get; set; }
        [Required(ErrorMessage = "Phải nhập")]
        [Range(1,long.MaxValue)]
        public decimal DonGia { get; set; }
        [Required(ErrorMessage = "Phải nhập")]
        [Range(0,int.MaxValue)]
        public int SoLuongTon { get; set; }
        // Viết hàm kiểm tra thể loại 5-50 ký tự
        public bool KTTheLoai()
        {           
            if (this.TheLoai.Length >= 5 && this.TheLoai.Length <= 50) return true;
            return false;
        }    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBanSach> HoaDonBanSaches { get; set; }
    }
}
